Issue 2 view entries - Lyn Kim
lyn-kim/code-journal pull request #6
Opened 2021-12-22 22:45 UTC by lyn-kim

![code-journal-issue-2-desktop](https://user-images.githubusercontent.com/89041368/147163339-e4b6faef-4a20-4172-8f97-985f187e57e1.gif)
![code-journal-issue-2-mobile](https://user-images.githubusercontent.com/89041368/147163345-64979a50-a1cc-4001-bfb1-98460de82865.gif)

2021-12-22 22:55 UTC, lyn-kim commented
![code-journal-issue-2-mobile2](https://user-images.githubusercontent.com/89041368/147164089-1bc8a408-02bc-4618-9ec2-7fe7b2e787f2.gif)

Edited padding for mobile-view text input box.

2021-12-22 23:00 UTC, codingcodymiller requested changes

2021-12-22 23:00 UTC, codingcodymiller commented on css/styles.css
> +
This shouldn't be necessary 🤔

2021-12-22 23:00 UTC, codingcodymiller commented on js/main.js
> +  singleEntry.innerHTML = '';
What is `singleEntry`? Why is this necessary?

2021-12-22 23:00 UTC, codingcodymiller commented on js/main.js
> +  singleEntry.innerHTML = '';
Ah I see, it's the list element. Instead of destroying all your prior entries just to recreate all of them, you should just make one new DOM tree for the entry that was just created, and add it to the top of the list.

2021-12-22 23:00 UTC, codingcodymiller commented on js/main.js
> +function showEntries(dataView) {
How about `switchView`? This function does more than show entries.

2021-12-22 23:00 UTC, codingcodymiller commented on js/main.js
> +function showEntryForm(dataView) {
This function is exactly the same as `showEntries` 👀

2021-12-22 23:00 UTC, codingcodymiller commented on js/main.js
>  }
Once you rename the function as I told you in my other comment, you can delete this function, and just use `switchView`

2021-12-22 23:00 UTC, codingcodymiller commented on js/main.js
> +  event.preventDefault();
Why is it necessary to prevent default here?

2021-12-23 01:49 UTC, lyn-kim commented
![Code-journal-empty-list-message](https://user-images.githubusercontent.com/89041368/147175271-b06682c6-2363-48bd-936e-c9487debe69e.JPG)

"No entries have been recorded." is now hidden upon first entry.

2021-12-23 01:53 UTC, codingcodymiller approved these changes

2021-12-23 01:55 UTC, merged